### ISSUE TITLE
Sometimes the build number is replaced.

### ISSUE THREAD

**Issue by eproulx-bb** [AlexStormwood/UnityAutomatedSemver#13]
My game was build version 0.3.11 (both buildVersion and buildNumber: Standalone). But after the nightly build, now the build version is 0.0.281 instead of the correct one 0.3.12.

It worked fine the day before (started off with 0.3.10 and ended up with 0.3.11).

This is the step in the build:

```
      - name: Find ProjectSettings.asset & increment its bundleVersion number
        uses: AlexStormwood/UnityAutomatedSemver@v1.1.1
        id: semver-update
        with:
          semver-update-type: 'patch'
```

I don't see any error during the build.
