### ISSUE TITLE
[Enhancement Suggestion] Only Pull the Config file and make changes to it.

### ISSUE THREAD

**Issue by Warhammer4000** [AlexStormwood/UnityAutomatedSemver#8]
### Context
The repo I'm working on has grown a bit. It takes almost 9min to do checkout. However, since we are just updating one single file I was wondering if it'd be possible to just get the config file. Make changes to it. and push it back. 

### Findings
Apparently it does seem possible. At least getting the file is https://stackoverflow.com/questions/16230838/is-it-possible-to-pull-just-one-file-in-git

Also with help of ChatGPT I found something like this 

```
 - name: Checkout Repository with Sparse Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          sparse-checkout: 'path/to/your-directory/'  # Adjust this to the directory of your file
```
### Suggestions
With this sparse checkout each user can just modify their own workflow to make it work. However, I felt like it'd be a really great addition to this workflow if it had this built in.

**Comment by AlexStormwood** [comment]
Always love seeing how you're using this action, thankyou for the enhancement suggestion :) 

Am I right in understanding this idea as just changing where the checkout happens within an action's job?

This is how a job typically runs right now: 
- Step 1: Checkout action
- Step 2: Action that operates on checked out files

Enhancement idea:
- Step 1: Action that checks out files _and_ operates on them

A sparse checkout does sound like the best thing to do for using this action in both scenarios, at least.
But I don't know of any packages that work in the enhancement suggestion style - I'll have a look around for some in the morning.

Assuming you've already split the semver stuff into its own lil semver-and-commit job or workflow, the only other thing that might help your long checkout times is implementing a cache into your actions; 
- using the cache action: https://github.com/actions/checkout/issues/1314 
- using workflow artifacts as a cache: https://github.com/actions/checkout/discussions/259

**Comment by Warhammer4000** [comment]
Okay I think just updating documentation would do the trick.
I did this 
```
 - name: Checkout 
        uses: actions/checkout@v4
        with:
          sparse-checkout: ProjectSettings
```          
**And this is the time difference**

![image](https://github.com/AlexStormwood/UnityAutomatedSemver/assets/12670678/897975ad-fe65-4af3-80f8-ec65c9361987)

I'm not exactly sure if it'd be the right approach embed the checkout part of the workflow in the action. If we really wanna push it, it's possible to just get the file. However I'm not exactly sure how it'd turn out without the directory when we push it back.

![image](https://github.com/AlexStormwood/UnityAutomatedSemver/assets/12670678/cba9b0cb-014b-475f-84fa-b1051b2fecd3)

**Comment by Warhammer4000** [comment]
> Always love seeing how you're using this action, thankyou for the enhancement suggestion :)
> 
> Am I right in understanding this idea as just changing where the checkout happens within an action's job?
> 
> This is how a job typically runs right now:
> 
> * Step 1: Checkout action
> * Step 2: Action that operates on checked out files
> 
> Enhancement idea:
> 
> * Step 1: Action that checks out files _and_ operates on them
> 
> A sparse checkout does sound like the best thing to do for using this action in both scenarios, at least. But I don't know of any packages that work in the enhancement suggestion style - I'll have a look around for some in the morning.
> 
> Assuming you've already split the semver stuff into its own lil semver-and-commit job or workflow, the only other thing that might help your long checkout times is implementing a cache into your actions;
> 
> * using the cache action: [Reuse/cache existing repository instead of always removing it? actions/checkout#1314](https://github.com/actions/checkout/issues/1314)
> * using workflow artifacts as a cache: [Caching results actions/checkout#259](https://github.com/actions/checkout/discussions/259)

Also, here's how my workflow looks right now. Not using cache for this. cache for builder workflows

```
name: Update Unity project semantic versioning

on:
  push:
    branches:
      - main
      - feature

jobs:
  semver:
    name: Update semver
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
        with:
          sparse-checkout: ProjectSettings

      - name: Determine semver update type based on branch
        id: determine-semver-update
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "::set-output name=semver-update-type::minor"
          elif [[ ${{ github.ref }} == 'refs/heads/feature' ]]; then
            echo "::set-output name=semver-update-type::patch"
          fi

      - name: Find ProjectSettings.asset & increment its bundleVersion number
        uses: AlexStormwood/UnityAutomatedSemver@v1.1.1
        id: semver-update
        with:
          semver-update-type: ${{ steps.determine-semver-update.outputs.semver-update-type }} 
          project-settings-path: 'ProjectSettings/ProjectSettings.asset'
          should-add-ms-store-trailing-zero: true

      - name: Get the new semver number
        run: echo "The new semver number for this Unity project is ${{ steps.semver-update.outputs.semver-number }}"

      - name: Push changed files back to repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated semver via automated action."
          git push origin HEAD:${{ github.ref }}


  store-pr-job:
    if: github.ref == 'refs/heads/main'
    needs: semver
    name: PR-Request-Matrix
    strategy:
      matrix:
        branch:
          - itch-io
          - xbox-one
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-to-store-branches
        uses: vsoch/pull-request-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: ${{ matrix.branch }}
          PULL_REQUEST_FROM_BRANCH: "main"
```

**Comment by AlexStormwood** [comment]
Wicked :) 

An update to the documentation is much simpler, I've just put that in place now.

In theory, checking out the single file with a sparse checkout should also be fine. Sparse checkouts apparently preserve the paths of whatever you checked out? I'm not sure, haven't tested it myself.

I just wanna hammer home the idea that "if the `ProjectSettings.asset` file is in the action runner workspace _somewhere_, then this action can work" and let developers sort out their own needs from that.

**Comment by Warhammer4000** [comment]
Just tested doing this works 
```
- name: Checkout 
        uses: actions/checkout@v4
        with:
          sparse-checkout: ProjectSettings.asset
          sparse-checkout-cone-mode: false
```
Cloning the File vs the Project Settings Directory has like a total of 5 sec difference that's all.
